name: Deploy PIMS Cloud API

on:
  push:
    branches:
      - staging
      - master

jobs:
  deploy_production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p apps/pims-cloud-api && cd apps/pims-cloud-api
            
            if [ -d ".git" ]; then
              git stash
              git pull origin master
            else
              git clone -b master https://github.com/yonathanth/back3-cloud-api.git .
            fi
            
            cd back3-cloud-api
            npm install --force
            
            # Run Prisma migrations
            npx prisma generate
            npx prisma migrate deploy
            
            # Build the application
            npm run build

            pid=$(pm2 pid "pims-cloud-api" 2>/dev/null)
            if [ -n "$pid" ]; then
              echo "Reloading pims-cloud-api"
              pm2 reload "pims-cloud-api"
              pm2 save
            else
              echo "New application"
              pm2 start npm --name "pims-cloud-api" -- start
              pm2 startup
              pm2 save
            fi
